version: "3"
services:
  web:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./build:/usr/share/nginx/html
    depends_on:
      - backend
  backend:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRESQL_PASSWORD}@postgres/postgres
      - PORT=8000
      - BOT_CREDENTIALS=${BOT_CREDENTIALS}
      - ADMIN_CREDENTIALS=${ADMIN_CREDENTIALS}
      - GAME_GLOBAL_START_T=${GAME_GLOBAL_START_T}
      - GAME_GLOBAL_END_T=${GAME_GLOBAL_END_T}
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
  postgres:
    image: bitnami/postgresql
    volumes:
      - postgresdb:/var/lib/postgresql/data
    environment:
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
volumes:
  postgresdb: {}
