version: "3"
services:
  web:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./build:/usr/share/nginx/html
    depends_on:
      - backend
  backend:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres/postgres
      - PORT=8000
      - BOT_CREDENTIALS=botbotbot
      - ADMIN_CREDENTIALS=hellodankness
      - GAME_GLOBAL_START_T='2022-10-20T00:09:36.150Z'
      - GAME_GLOBAL_END_T='2022-11-20T00:09:36.150Z'
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
  postgres:
    image: bitnami/postgresql
    volumes:
      - postgresdb:/var/lib/postgresql/data
    environment:
      - POSTGRESQL_PASSWORD=postgres
volumes:
  postgresdb: {}