import { GameRelay } from './game';
import { strategy } from './strategy';
import { ClientFactoryRelay } from '../../common/client_factory';
import { InProgressRelay } from '../../client/components/teamstates/InProgressRelay';

let description = <p className="text-justify">
</p>

export const { Client:RelayClient_C, ClientWithBot:RelayClientWithBot_C, OnlineClient:RelayOnlineClient_C } = ClientFactoryRelay({...GameRelay, name: "relay_c"}, InProgressRelay, strategy("C"), description);
export const { Client:RelayClient_D, ClientWithBot:RelayClientWithBot_D, OnlineClient:RelayOnlineClient_D } = ClientFactoryRelay({...GameRelay, name: "relay_d"}, InProgressRelay, strategy("D"), description);
export const { Client:RelayClient_E, ClientWithBot:RelayClientWithBot_E, OnlineClient:RelayOnlineClient_E } = ClientFactoryRelay({...GameRelay, name: "relay_e"}, InProgressRelay, strategy("E"), description);


export const { Client:RelayClient_1_D_B, ClientWithBot:RelayClientWithBot_1_D_B, OnlineClient:RelayOnlineClient_1_D_B } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("1_D_B"), description);
export const { Client:RelayClient_1_D_C, ClientWithBot:RelayClientWithBot_1_D_C, OnlineClient:RelayOnlineClient_1_D_C } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("1_D_C"), description);
export const { Client:RelayClient_1_D_D, ClientWithBot:RelayClientWithBot_1_D_D, OnlineClient:RelayOnlineClient_1_D_D } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("1_D_D"), description);
export const { Client:RelayClient_2_D_B, ClientWithBot:RelayClientWithBot_2_D_B, OnlineClient:RelayOnlineClient_2_D_B } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("2_D_B"), description);
export const { Client:RelayClient_2_D_C, ClientWithBot:RelayClientWithBot_2_D_C, OnlineClient:RelayOnlineClient_2_D_C } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("2_D_C"), description);
export const { Client:RelayClient_2_D_D, ClientWithBot:RelayClientWithBot_2_D_D, OnlineClient:RelayOnlineClient_2_D_D } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("2_D_D"), description);
export const { Client:RelayClient_3_D_B, ClientWithBot:RelayClientWithBot_3_D_B, OnlineClient:RelayOnlineClient_3_D_B } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("3_D_B"), description);
export const { Client:RelayClient_3_D_C, ClientWithBot:RelayClientWithBot_3_D_C, OnlineClient:RelayOnlineClient_3_D_C } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("3_D_C"), description);
export const { Client:RelayClient_3_D_D, ClientWithBot:RelayClientWithBot_3_D_D, OnlineClient:RelayOnlineClient_3_D_D } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("3_D_D"), description);
export const { Client:RelayClient_4_D_B, ClientWithBot:RelayClientWithBot_4_D_B, OnlineClient:RelayOnlineClient_4_D_B } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("4_D_B"), description);
export const { Client:RelayClient_4_D_C, ClientWithBot:RelayClientWithBot_4_D_C, OnlineClient:RelayOnlineClient_4_D_C } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("4_D_C"), description);
export const { Client:RelayClient_4_D_D, ClientWithBot:RelayClientWithBot_4_D_D, OnlineClient:RelayOnlineClient_4_D_D } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("4_D_D"), description);
export const { Client:RelayClient_5_D_A, ClientWithBot:RelayClientWithBot_5_D_A, OnlineClient:RelayOnlineClient_5_D_A } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("5_D_A"), description);
export const { Client:RelayClient_5_D_B, ClientWithBot:RelayClientWithBot_5_D_B, OnlineClient:RelayOnlineClient_5_D_B } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("5_D_B"), description);
export const { Client:RelayClient_5_D_C, ClientWithBot:RelayClientWithBot_5_D_C, OnlineClient:RelayOnlineClient_5_D_C } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("5_D_C"), description);
export const { Client:RelayClient_5_D_D, ClientWithBot:RelayClientWithBot_5_D_D, OnlineClient:RelayOnlineClient_5_D_D } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("5_D_D"), description);
export const { Client:RelayClient_6_D_A, ClientWithBot:RelayClientWithBot_6_D_A, OnlineClient:RelayOnlineClient_6_D_A } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("6_D_A"), description);
export const { Client:RelayClient_6_D_B, ClientWithBot:RelayClientWithBot_6_D_B, OnlineClient:RelayOnlineClient_6_D_B } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("6_D_B"), description);
export const { Client:RelayClient_6_D_C, ClientWithBot:RelayClientWithBot_6_D_C, OnlineClient:RelayOnlineClient_6_D_C } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("6_D_C"), description);
export const { Client:RelayClient_6_D_D, ClientWithBot:RelayClientWithBot_6_D_D, OnlineClient:RelayOnlineClient_6_D_D } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("6_D_D"), description);
export const { Client:RelayClient_7_D_A, ClientWithBot:RelayClientWithBot_7_D_A, OnlineClient:RelayOnlineClient_7_D_A } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("7_D_A"), description);
export const { Client:RelayClient_7_D_B, ClientWithBot:RelayClientWithBot_7_D_B, OnlineClient:RelayOnlineClient_7_D_B } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("7_D_B"), description);
export const { Client:RelayClient_7_D_C, ClientWithBot:RelayClientWithBot_7_D_C, OnlineClient:RelayOnlineClient_7_D_C } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("7_D_C"), description);
export const { Client:RelayClient_7_H_A, ClientWithBot:RelayClientWithBot_7_H_A, OnlineClient:RelayOnlineClient_7_H_A } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("7_H_A"), description);
export const { Client:RelayClient_7_H_B, ClientWithBot:RelayClientWithBot_7_H_B, OnlineClient:RelayOnlineClient_7_H_B } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("7_H_B"), description);
export const { Client:RelayClient_8_D_A, ClientWithBot:RelayClientWithBot_8_D_A, OnlineClient:RelayOnlineClient_8_D_A } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("8_D_A"), description);
export const { Client:RelayClient_8_D_B, ClientWithBot:RelayClientWithBot_8_D_B, OnlineClient:RelayOnlineClient_8_D_B } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("8_D_B"), description);
export const { Client:RelayClient_8_D_C, ClientWithBot:RelayClientWithBot_8_D_C, OnlineClient:RelayOnlineClient_8_D_C } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("8_D_C"), description);
export const { Client:RelayClient_8_D_D, ClientWithBot:RelayClientWithBot_8_D_D, OnlineClient:RelayOnlineClient_8_D_D } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("8_D_D"), description);
export const { Client:RelayClient_8_H_A, ClientWithBot:RelayClientWithBot_8_H_A, OnlineClient:RelayOnlineClient_8_H_A } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("8_H_A"), description);
export const { Client:RelayClient_8_H_B, ClientWithBot:RelayClientWithBot_8_H_B, OnlineClient:RelayOnlineClient_8_H_B } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("8_H_B"), description);
export const { Client:RelayClient_9_D_A, ClientWithBot:RelayClientWithBot_9_D_A, OnlineClient:RelayOnlineClient_9_D_A } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("9_D_A"), description);
export const { Client:RelayClient_9_D_B, ClientWithBot:RelayClientWithBot_9_D_B, OnlineClient:RelayOnlineClient_9_D_B } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("9_D_B"), description);
export const { Client:RelayClient_9_D_C, ClientWithBot:RelayClientWithBot_9_D_C, OnlineClient:RelayOnlineClient_9_D_C } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("9_D_C"), description);
export const { Client:RelayClient_9_D_Cp, ClientWithBot:RelayClientWithBot_9_D_Cp, OnlineClient:RelayOnlineClient_9_D_Cp } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("9_D_Cp"), description);
export const { Client:RelayClient_9_D_D, ClientWithBot:RelayClientWithBot_9_D_D, OnlineClient:RelayOnlineClient_9_D_D } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("9_D_D"), description);
export const { Client:RelayClient_9_D_Dp, ClientWithBot:RelayClientWithBot_9_D_Dp, OnlineClient:RelayOnlineClient_9_D_Dp } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("9_D_Dp"), description);
export const { Client:RelayClient_9_H_A, ClientWithBot:RelayClientWithBot_9_H_A, OnlineClient:RelayOnlineClient_9_H_A } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("9_H_A"), description);
export const { Client:RelayClient_9_H_B, ClientWithBot:RelayClientWithBot_9_H_B, OnlineClient:RelayOnlineClient_9_H_B } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("9_H_B"), description);
export const { Client:RelayClient_10_D_A, ClientWithBot:RelayClientWithBot_10_D_A, OnlineClient:RelayOnlineClient_10_D_A } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("10_D_A"), description);
export const { Client:RelayClient_10_D_B, ClientWithBot:RelayClientWithBot_10_D_B, OnlineClient:RelayOnlineClient_10_D_B } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("10_D_B"), description);
export const { Client:RelayClient_10_D_C, ClientWithBot:RelayClientWithBot_10_D_C, OnlineClient:RelayOnlineClient_10_D_C } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("10_D_C"), description);
export const { Client:RelayClient_10_D_Cp, ClientWithBot:RelayClientWithBot_10_D_Cp, OnlineClient:RelayOnlineClient_10_D_Cp } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("10_D_Cp"), description);
export const { Client:RelayClient_10_D_D, ClientWithBot:RelayClientWithBot_10_D_D, OnlineClient:RelayOnlineClient_10_D_D } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("10_D_D"), description);
export const { Client:RelayClient_10_D_Dp, ClientWithBot:RelayClientWithBot_10_D_Dp, OnlineClient:RelayOnlineClient_10_D_Dp } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("10_D_Dp"), description);
export const { Client:RelayClient_10_H_A, ClientWithBot:RelayClientWithBot_10_H_A, OnlineClient:RelayOnlineClient_10_H_A } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("10_H_A"), description);
export const { Client:RelayClient_10_H_B, ClientWithBot:RelayClientWithBot_10_H_B, OnlineClient:RelayOnlineClient_10_H_B } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("10_H_B"), description);
export const { Client:RelayClient_11_D_A, ClientWithBot:RelayClientWithBot_11_D_A, OnlineClient:RelayOnlineClient_11_D_A } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("11_D_A"), description);
export const { Client:RelayClient_11_D_B, ClientWithBot:RelayClientWithBot_11_D_B, OnlineClient:RelayOnlineClient_11_D_B } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("11_D_B"), description);
export const { Client:RelayClient_11_D_C, ClientWithBot:RelayClientWithBot_11_D_C, OnlineClient:RelayOnlineClient_11_D_C } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("11_D_C"), description);
export const { Client:RelayClient_11_D_Cp, ClientWithBot:RelayClientWithBot_11_D_Cp, OnlineClient:RelayOnlineClient_11_D_Cp } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("11_D_Cp"), description);
export const { Client:RelayClient_11_D_D, ClientWithBot:RelayClientWithBot_11_D_D, OnlineClient:RelayOnlineClient_11_D_D } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("11_D_D"), description);
export const { Client:RelayClient_11_D_Dp, ClientWithBot:RelayClientWithBot_11_D_Dp, OnlineClient:RelayOnlineClient_11_D_Dp } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("11_D_Dp"), description);
export const { Client:RelayClient_11_H_A, ClientWithBot:RelayClientWithBot_11_H_A, OnlineClient:RelayOnlineClient_11_H_A } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("11_H_A"), description);
export const { Client:RelayClient_11_H_B, ClientWithBot:RelayClientWithBot_11_H_B, OnlineClient:RelayOnlineClient_11_H_B } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("11_H_B"), description);
export const { Client:RelayClient_12_D_A, ClientWithBot:RelayClientWithBot_12_D_A, OnlineClient:RelayOnlineClient_12_D_A } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("12_D_A"), description);
export const { Client:RelayClient_12_D_B, ClientWithBot:RelayClientWithBot_12_D_B, OnlineClient:RelayOnlineClient_12_D_B } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("12_D_B"), description);
export const { Client:RelayClient_12_D_C, ClientWithBot:RelayClientWithBot_12_D_C, OnlineClient:RelayOnlineClient_12_D_C } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("12_D_C"), description);
export const { Client:RelayClient_12_D_D, ClientWithBot:RelayClientWithBot_12_D_D, OnlineClient:RelayOnlineClient_12_D_D } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("12_D_D"), description);
export const { Client:RelayClient_12_D_E, ClientWithBot:RelayClientWithBot_12_D_E, OnlineClient:RelayOnlineClient_12_D_E } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("12_D_E"), description);
export const { Client:RelayClient_12_D_Ep, ClientWithBot:RelayClientWithBot_12_D_Ep, OnlineClient:RelayOnlineClient_12_D_Ep } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("12_D_Ep"), description);
export const { Client:RelayClient_12_H_A, ClientWithBot:RelayClientWithBot_12_H_A, OnlineClient:RelayOnlineClient_12_H_A } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("12_H_A"), description);
export const { Client:RelayClient_12_H_B, ClientWithBot:RelayClientWithBot_12_H_B, OnlineClient:RelayOnlineClient_12_H_B } = ClientFactoryRelay(GameRelay, InProgressRelay, strategy("12_H_B"), description);
