# https://github.com/marketplace/actions/lint-action
name: Build

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-builders:
    name: Run builders
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run (client) build
        # CI was true -> treat warnings as errors. Not for now.
        run: CI= npm run build

      - name: Run (server)
        run: npm run dev:server -- -- sanity-check
