name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Node.js dependencies
        run: npm ci
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          commit: false
          eslint_dir: "src/"
          eslint_extensions: "js,ts,jsx,tsx"

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Node.js dependencies
        run: npm ci
      - name: Run (client) build
        run: npm run build
      - name: Run (server)
        run: PUBLIC_URL=https://localhost/ npm run check:server

  tests:
    name: client tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Node.js dependencies
        run: npm ci
      - name: Run (client) tests
        run: npm run test
