name: sync

on:
  release:
    types: [published]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync release with private repository
        run: |
            # Check if PRIVATE_REPO_NAME is set
            if [ -z "${{ secrets.PRIVATE_REPO_NAME }}" ]; then
              echo "Error: PRIVATE_REPO_NAME secret is not set"
              exit 0
            fi
            
            echo "Syncing release ${{ github.event.release.tag_name }} to private repository"
            
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git clone https://github.com/a-gondolkodas-orome/durer-aion.git public-repo
            cd public-repo
            git checkout ${{ github.event.release.tag_name }}
            git remote add private https://x-access-token:${{ secrets.PRIVATE_PAT }}@github.com/${{ secrets.PRIVATE_REPO_NAME }}.git
            git remote update
            
            # Push the tag and the associated commit to private repository
            git push private ${{ github.event.release.tag_name }}
            
            # Also push the main branch if this release is from main
            git checkout main
            if git show-ref --quiet refs/remotes/private/main; then
              git merge private/main -X ours -m "Sync from public repository"
            fi
            git push private main

