name: sync

on:
  push:
    branches:
      - main
      - sync-*

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:

      - name: Sync with private repository
        run: |
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git clone https://github.com/a-gondolkodas-orome/durer-aion.git public-repo
            cd public-repo
            git checkout ${{ github.ref_name }}
            git remote add private https://x-access-token:${{ secrets.PRIVATE_PAT }}@github.com/${{ secrets.PRIVATE_REPO_NAME }}.git
            git remote update
            if git show-ref --quiet refs/remotes/private/${{ github.ref_name }}; then
              git merge private/${{ github.ref_name }} -X ours -m "Sync from public repository"
            fi
            git push private ${{ github.ref_name }}
